services:
  data-generator:
    image: 'timescale-benchmark'
    build: .
    container_name: timescale-benchmark
    environment:
      CONN_STRING: "postgresql://postgres:5432/TEST?user=postgres&password=TEST!timescale"
    volumes:
      - .:/app
    command: ["--devices", "300", "--tags", "50", "--years", "3", "--test-devices", "10"]
    depends_on:
      postgres:
        condition: service_healthy
    
  postgres:
    shm_size: '3gb'
    image: timescale/timescaledb-ha:pg16
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: TEST!timescale
      POSTGRES_DB: TEST
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 10s
      retries: 10
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgresql.conf:/etc/postgresql/postgresql.conf
    command: postgres -c 'config_file=/etc/postgresql/postgresql.conf'

volumes:
  postgres_data:
    name: postgres_data
    # Add this driver option to always start fresh
    driver_opts:
      type: tmpfs
      device: tmpfs

networks:
  default:
    name: test-network
